// import { YahooFinance } from "@src/clients/yahooFinance";
// import yahooFinanceNormalizedFixture from '@test/fixtures/yahoofinancenormalized_asset.json'

// jest.mock('@/src/clients/yahooFinance');

// describe('asset Service', () => {
//     it('Should return price for a list of assets', async() => {
        
//         YahooFinance.prototype.fetchName = jest
//             .fn()
//             .mockResolvedValue(yahooFinanceNormalizedFixture);
        
//         const asset = {
//             "asset": "ITUB3.SA",
//             "regularMarketPrice": 21.85,                
//             "currency": "BRL",
//             "regularMarketDayHigh": 21.88,
//             "regularMarketDayLow": 21.52,
//             "regularMarketOpen": 21.57,
//             "longName": "Itaú Unibanco Holding S.A."
//         }

//         const expectedResponse = [
//             {
//                 "quoteResponse": {
//                     "result": [
//                         {
//                             "language": "pt-BR",
//                             "region": "BR",
//                             "quoteType": "EQUITY",
//                             "typeDisp": "Ação",
//                             "quoteSourceName": "Nasdaq Real Time Price",
//                             "triggerable": false,
//                             "customPriceAlertConfidence": "NONE",
//                             "financialCurrency": "USD",
//                             "regularMarketOpen": 130.92,
//                             "averageDailyVolume3Month": 86542825,
//                             "averageDailyVolume10Day": 89022860,
//                             "fiftyTwoWeekLowChange": 2.8200073,
//                             "fiftyTwoWeekLowChangePercent": 0.021853747,
//                             "fiftyTwoWeekRange": "129.04 - 182.94",
//                             "fiftyTwoWeekHighChange": -51.08,
//                             "fiftyTwoWeekHighChangePercent": -0.27921724,
//                             "fiftyTwoWeekLow": 129.04,
//                             "fiftyTwoWeekHigh": 182.94,
//                             "dividendDate": 1668038400,
//                             "earningsTimestamp": 1666904400,
//                             "earningsTimestampStart": 1674644340,
//                             "earningsTimestampEnd": 1675080000,
//                             "trailingAnnualDividendRate": 0.9,
//                             "trailingPE": 21.581015,
//                             "trailingAnnualDividendYield": 0.0068063224,
//                             "epsTrailingTwelveMonths": 6.11,
//                             "epsForward": 6.77,
//                             "epsCurrentYear": 6.2,
//                             "priceEpsCurrentYear": 21.267742,
//                             "sharesOutstanding": 15908100096,
//                             "bookValue": 3.178,
//                             "fiftyDayAverage": 144.1318,
//                             "fiftyDayAverageChange": -12.271805,
//                             "fiftyDayAverageChangePercent": -0.08514293,
//                             "twoHundredDayAverage": 152.1331,
//                             "twoHundredDayAverageChange": -20.273102,
//                             "twoHundredDayAverageChangePercent": -0.13325898,
//                             "marketCap": 2097642078208,
//                             "forwardPE": 19.477104,
//                             "priceToBook": 41.491505,
//                             "sourceInterval": 15,
//                             "exchangeDataDelayedBy": 0,
//                             "currency": "USD",
//                             "postMarketChangePercent": -0.128923,
//                             "postMarketTime": 1671843598,
//                             "postMarketPrice": 131.69,
//                             "postMarketChange": -0.169998,
//                             "regularMarketChange": -0.36999512,
//                             "regularMarketTime": 1671829204,
//                             "regularMarketDayHigh": 132.41,
//                             "regularMarketDayRange": "129.64 - 132.41",
//                             "regularMarketDayLow": 129.64,
//                             "regularMarketVolume": 63674050,
//                             "regularMarketPreviousClose": 132.23,
//                             "bid": 131.73,
//                             "ask": 131.7,
//                             "bidSize": 11,
//                             "askSize": 9,
//                             "fullExchangeName": "NasdaqGS",
//                             "exchange": "NMS",
//                             "shortName": "Apple Inc.",
//                             "longName": "Apple Inc.",
//                             "messageBoardId": "finmb_24937_lang_pt",
//                             "exchangeTimezoneName": "America/New_York",
//                             "market": "us_market",
//                             "marketState": "CLOSED",
//                             "exchangeTimezoneShortName": "EST",
//                             "gmtOffSetMilliseconds": -18000000,
//                             "esgPopulated": false,
//                             "regularMarketChangePercent": -0.2798118,
//                             "regularMarketPrice": 131.86,
//                             "firstTradeDateMilliseconds": 345479400000,
//                             "priceHint": 2,
//                             "averageAnalystRating": "1.9 - Buy",
//                             "tradeable": false,
//                             "cryptoTradeable": false,
//                             "displayName": "Apple",
//                             "symbol": "AAPL"
//                         },
//                         {
//                             "language": "pt-BR",
//                             "region": "BR",
//                             "quoteType": "CRYPTOCURRENCY",
//                             "typeDisp": "Cryptocurrency",
//                             "quoteSourceName": "CoinMarketCap",
//                             "triggerable": false,
//                             "customPriceAlertConfidence": "NONE",
//                             "regularMarketOpen": 16794.287,
//                             "averageDailyVolume3Month": 32003038108,
//                             "averageDailyVolume10Day": 18251543003,
//                             "startDate": 1367107200,
//                             "coinImageUrl": "https://s2.coinmarketcap.com/static/img/coins/64x64/1.png",
//                             "logoUrl": "https://s2.coinmarketcap.com/static/img/coins/64x64/1.png",
//                             "fiftyTwoWeekLowChange": 1239.7363,
//                             "fiftyTwoWeekLowChangePercent": 0.079475135,
//                             "fiftyTwoWeekRange": "15599.047 - 51956.33",
//                             "fiftyTwoWeekHighChange": -35117.547,
//                             "fiftyTwoWeekHighChangePercent": -0.6759051,
//                             "fiftyTwoWeekLow": 15599.047,
//                             "fiftyTwoWeekHigh": 51956.33,
//                             "fiftyDayAverage": 17178.717,
//                             "fiftyDayAverageChange": -339.9336,
//                             "fiftyDayAverageChangePercent": -0.019788066,
//                             "twoHundredDayAverage": 20173.004,
//                             "twoHundredDayAverageChange": -3334.2207,
//                             "twoHundredDayAverageChangePercent": -0.16528133,
//                             "marketCap": 324013522944,
//                             "sourceInterval": 15,
//                             "exchangeDataDelayedBy": 0,
//                             "currency": "USD",
//                             "regularMarketChange": -38.11328,
//                             "regularMarketTime": 1671888120,
//                             "regularMarketDayHigh": 16855.217,
//                             "regularMarketDayRange": "16794.287 - 16855.217",
//                             "regularMarketDayLow": 16794.287,
//                             "regularMarketVolume": 13696697344,
//                             "regularMarketPreviousClose": 16794.287,
//                             "fullExchangeName": "CCC",
//                             "exchange": "CCC",
//                             "shortName": "Bitcoin USD",
//                             "messageBoardId": "finmb_BTC_CCC_lang_pt",
//                             "exchangeTimezoneName": "UTC",
//                             "market": "ccc_market",
//                             "marketState": "REGULAR",
//                             "exchangeTimezoneShortName": "UTC",
//                             "gmtOffSetMilliseconds": 0,
//                             "esgPopulated": false,
//                             "regularMarketChangePercent": -0.22583573,
//                             "regularMarketPrice": 16838.783,
//                             "firstTradeDateMilliseconds": 1410912000000,
//                             "priceHint": 2,
//                             "circulatingSupply": 19242100,
//                             "lastMarket": "CoinMarketCap",
//                             "volume24Hr": 13696697344,
//                             "volumeAllCurrencies": 13696697344,
//                             "fromCurrency": "BTC",
//                             "toCurrency": "USD=X",
//                             "coinMarketCapLink": "https://coinmarketcap.com/currencies/bitcoin",
//                             "tradeable": false,
//                             "cryptoTradeable": true,
//                             "symbol": "BTC-USD"
//                         },
//                         {
//                             "language": "en-US",
//                             "region": "US",
//                             "quoteType": "CURRENCY",
//                             "typeDisp": "Currency",
//                             "quoteSourceName": "Delayed Quote",
//                             "triggerable": true,
//                             "customPriceAlertConfidence": "HIGH",
//                             "currency": "USD",
//                             "regularMarketOpen": 1.0607828,
//                             "fiftyTwoWeekLow": 0.9540164,
//                             "fiftyTwoWeekHigh": 1.1494253,
//                             "fiftyDayAverage": 1.0238967,
//                             "twoHundredDayAverage": 1.032387,
//                             "regularMarketChange": 0.002592802,
//                             "regularMarketDayHigh": 1.0634904,
//                             "regularMarketDayLow": 1.0590976,
//                             "regularMarketPreviousClose": 1.0604453,
//                             "bid": 1.0630381,
//                             "ask": 1.0624734,
//                             "shortName": "EUR/USD",
//                             "regularMarketChangePercent": 0.24450132,
//                             "regularMarketPrice": 1.0630381,
//                             "averageDailyVolume3Month": 0,
//                             "averageDailyVolume10Day": 0,
//                             "fiftyTwoWeekLowChange": 0.07069999,
//                             "fiftyTwoWeekLowChangePercent": 0.07410773,
//                             "fiftyTwoWeekRange": "0.9540164 - 1.1494253",
//                             "fiftyTwoWeekHighChange": -0.10750002,
//                             "fiftyTwoWeekHighChangePercent": -0.093525015,
//                             "fiftyDayAverageChange": -0.035961032,
//                             "fiftyDayAverageChangePercent": -0.03512174,
//                             "twoHundredDayAverageChange": -0.027928948,
//                             "twoHundredDayAverageChangePercent": -0.02705279,
//                             "sourceInterval": 15,
//                             "exchangeDataDelayedBy": 0,
//                             "regularMarketTime": 1671834584,
//                             "regularMarketDayRange": "1.0590976 - 1.0634904",
//                             "regularMarketVolume": 0,
//                             "bidSize": 0,
//                             "askSize": 0,
//                             "fullExchangeName": "CCY",
//                             "exchange": "CCY",
//                             "messageBoardId": "finmb_EUR_X",
//                             "exchangeTimezoneName": "Europe/London",
//                             "market": "ccy_market",
//                             "marketState": "CLOSED",
//                             "exchangeTimezoneShortName": "GMT",
//                             "gmtOffSetMilliseconds": 0,
//                             "esgPopulated": false,
//                             "firstTradeDateMilliseconds": 1070236800000,
//                             "priceHint": 4,
//                             "tradeable": false,
//                             "cryptoTradeable": false,
//                             "symbol": "EURUSD=X"
//                         }
//                     ],
//                     "error": null
//                 }
//             }
//         ]

//         const assets = new Asset(new YahooFinance());

//         expect(assets).toEqual(asset)
//     })
// })